services:
  tusk-api:
    build: .
    ports:
      - "8080:8081"
    environment:
      - APP_ENV=development
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: tusk
      POSTGRES_PASSWORD: tuskpass
      POSTGRES_DB: tusk
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tusk -d tusk"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: